version: "3.4"
services:
  frontend:
    build: ./frontend/
    container_name: frontend
    image: node:lts-alpine
    working_dir: /var/www/html/app/
    expose:
      - 8080
    volumes:
      - ./frontend/:/var/www/html/app
    tty: true

