version: '3.4'
services:
  frontend:
    build:
      context: ./frontend/
      dockerfile: Dockerfile-dev
    ports:
      - "5173:5173"
    container_name: frontend 
    volumes:
       - ./frontend:/App/frontend
       - /app/node_modules
