version: "3"
services:
  api:
    build: ./backend/
    env_file:
        - ./.env
    ports:
      - 8000:8000
    volumes:
      - ./backend:/backend/
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - db

  db:
    env_file:
        - ./.env
    image: postgres:alpine
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db:
