version: "3"
services:
  api:
    build: ./backend/
    env_file:
        - ./.env
    ports:
      - 8000:8000
    volumes:
      - ./:/usr/src/app
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - postgres

  postgres:
    env_file:
        - ./.env
    image: postgres
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db:
