"""create inital tables

Revision ID: 304fd4e0961b
Revises: 
Create Date: 2022-08-25 21:55:01.659815

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '304fd4e0961b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('document', sa.String(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('logged_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('document'),
    sa.UniqueConstraint('email')
    )
    op.create_table('payment_books',
    sa.Column('payment_book_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('is_payed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('payer_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.ForeignKeyConstraint(['payer_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('payment_book_id')
    )
    op.create_table('monthly_payments',
    sa.Column('monthly_payments_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('price', sa.Numeric(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('is_payed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('payment_book_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.ForeignKeyConstraint(['payment_book_id'], ['payment_books.payment_book_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('monthly_payments_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('monthly_payments')
    op.drop_table('payment_books')
    op.drop_table('users')
    # ### end Alembic commands ###
