"""create inital tables

Revision ID: 7e06cef28262
Revises: 976f73c82bf0
Create Date: 2022-08-25 20:24:59.758196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e06cef28262'
down_revision = '976f73c82bf0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
