"""Generate token table

Revision ID: fdbb5cc80315
Revises: 304fd4e0961b
Create Date: 2022-08-26 13:33:57.923270

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fdbb5cc80315'
down_revision = '304fd4e0961b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
